### ISSUE TITLE
Remove neos/nodetypes dependency

### ISSUE THREAD

**Issue by rolandschuetz** [1drop/Onedrop.AjaxForm#4]
Hello,

since quite a while the Neos.NodeTypes aren't really best practice anymore. In April the nodetypes got split up into separate packages. You are only using the Neos.NodeTypes:Form, so this could easily be refactored to only depend on [neos/nodetypes-form](https://github.com/neos/nodetypes-form).

**Comment by rolandschuetz** [comment]
Attention:
You just broke the package. When you only require the NodeTypes.Form package the names change to 'Neos.NodeTypes.Form:Form'.

Also this should cause a version bump to 4.0.0 for the next release ;)

**Comment by htuscher** [comment]
Now it should be fine.

**Comment by rolandschuetz** [comment]
Looks good, just one last place ;)
https://github.com/1drop/Onedrop.AjaxForm/blob/master/Resources/Private/Templates/AjaxForm/Index.html#L14

(I'm not using Onedrop.AjaxForm, so I haven't tested it locally)
